### ISSUE TITLE
I can't open the game

### ISSUE THREAD

**Issue by SadBoyMaisAlegre** [Admiral-Billy/Pokerogue-App#56] opened 2024-05-23 03:24 UTC
Hello, I'm using the mobile version released 3 days ago, and I can't play AT ALL, every time it loads to 100% and simply crashes, both in online and offline mode, what should I do ?

**Comment by Admiral-Billy** [comment] 2024-05-23 09:18
What Android version do you have? And the device name as well.

**Comment by SadBoyMaisAlegre** [comment] 2024-05-23 11:25
> What Android version do you have? And the device name as well.

I have a Samsung A10, Android 11 version

**Comment by Admiral-Billy** [comment] 2024-05-23 22:39
Hm, I'll have to look into this one more then; things are working normally for me on my S24 Ultra at least. Just in case, I'd try clearing the game's files and redownloading to see if that fixes anything; they're in android/data/com.example.pokerogue/files/game (and won't affect your save files).

**Comment by SadBoyMaisAlegre** [comment] 2024-05-24 02:26
ok try to do this, I've uninstalled and installed it before and it didn't work, I did it yesterday, but I'm going to look for this folder and clean these files.

**Comment by SadBoyMaisAlegre** [comment] 2024-05-24 02:40
> Hm, I'll have to look into this one more then; things are working normally for me on my S24 Ultra at least. Just in case, I'd try clearing the game's files and redownloading to see if that fixes anything; they're in android/data/com.example.pokerogue/files/game (and won't affect your save files).

I went to the folder, cleared everything, cleared the cache and the data, downloaded Futaba's Debug Build and the same problem is happening, reaching 100% and crashing the game, both in online and offline mode.

**Comment by SadBoyMaisAlegre** [comment] 2024-05-26 00:18
Do you have any idea what this could be?

**Comment by Admiral-Billy** [comment] 2024-05-26 06:56
I don't really know any specifics unfortunately. I haven't been able to replicate it, and as far as I can tell it's just *happening* for some users. Oftentimes it's because of hardware, but your device should be fine for this so I'm not really sure.

**Comment by SadBoyMaisAlegre** [comment] 2024-05-26 12:36
ok, If there is anything I can help with let me know

**Comment by SadBoyMaisAlegre** [comment] 2024-05-26 23:31
![Screenshot_20240526-202841_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/104371188/ff1f7e72-a5cd-4e39-9399-330e88bf1201)

I was trying and trying and there was a moment in offline mode, more or less when it was at 90+% and I left the app when I came back it was like this lmao

**Comment by Admiral-Billy** [comment] 2024-05-27 04:52
Yeah I think this happens any time the app gets "unloaded" from inactivity; the javascript never starts again so all you get is the blank html page.

**Comment by SadBoyMaisAlegre** [comment] 2024-05-27 13:02
hey, I installed version 2.4.0, it's very nice, the download and extraction percentage appears, I think it's cool, but I still can't enter it, but the online and offline buttons are written "using account save" or "local save" This is my first time playing, so I don't have a save, could this be the reason it's crashing?

**Comment by SadBoyMaisAlegre** [comment] 2024-05-28 01:02
hey, today I tried more times (goin insane) but I saw something new, I'm trying in offline mode and when it reached 100% it took a long time and then the controls and the screen with the same game background appeared but shortly afterwards the game crashed again. What I was doing before was uninstalling an app to see if it was a memory problem, and maybe it is, but do you already have 20% of the space freed up as needed?

**Comment by Admiral-Billy** [comment] 2024-05-28 04:05
Nah that's not an issue. That's just to clarify that online mode uses your account for all of its data, and offline mode uses whatever you happen on your device. Are both modes still crashing currently?

**Comment by SadBoyMaisAlegre** [comment] 2024-05-28 06:28
yes, both are crashing, always when reaching 100% loading, and no message appears from Android saying that the app has stopped or anything like that, it simply closes without explanation,EVERY TIME when reaching 100% loading

**Comment by Admiral-Billy** [comment] 2024-05-28 06:51
I see

There's still not a whole lot I can do without more reports and/or a consistent way to reproduce the issue on my side unfortunately. Does this happen for the browser version as well, or just the app?

**Comment by SadBoyMaisAlegre** [comment] 2024-05-28 12:17
I tested many browsers, my main one is the Kiwi browser, it uses Chromium as a base and looks like this (image) and the other one, which gave a different result, but a little similar,it was fire fox nightly (specifically the nightly version) it had the buttons like the kiwi browser in the image but the background was gray as if the game was going to load at some point but it will only stay on that screen gray
![Screenshot_20240527-102439_Kiwi Browser](https://github.com/Admiral-Billy/Pokerogue-App/assets/104371188/8c9302e9-56f3-4ed9-ad01-e2647dab21f4)

**Comment by SadBoyMaisAlegre** [comment] 2024-05-28 12:18
The many others I tested were the same as Kiwi Browser

**Comment by SadBoyMaisAlegre** [comment] 2024-05-28 21:47
hey, yesterday tried more times but I saw something new, but I didn't even comment because in the following attempts it followed the same way I commented:
I'm was trying in offline mode and when it reached 100% it took a long time and then the controls and the screen with the game background appeared but shortly afterwards the game crashed again. 
And Today with this new uptdade happened again, so what I was doing before was uninstalling some apps on my phone to see if it was a memory problem, but do you already have 20% of the space freed up as needed?

**Comment by Admiral-Billy** [comment] 2024-05-28 22:10
In terms of file size and ram usage, both are at around 1gb each I think.

**Comment by SadBoyMaisAlegre** [comment] 2024-05-28 22:58
now I have 6gb storage free, and ~550+ RAM memo, but I don't know how I'm going to increase this lol

**Comment by SadBoyMaisAlegre** [comment] 2024-05-29 00:12
![Screenshot_20240528-210446_Device care](https://github.com/Admiral-Billy/Pokerogue-App/assets/104371188/cce2c101-888f-4667-93d8-cd49a1bba443)

in the device and battery assistance area there are some statistics, and for the Pokerogue app it says, "failures frequent" "problem detected", but I can't see what the problem is ;-;

**Comment by Admiral-Billy** [comment] 2024-06-04 05:54
I gave someone a test version with some tweaks to how file handling is done, maybe see if it works for you? https://github.com/Admiral-Billy/Pokerogue-App/issues/68#issuecomment-2146668991

**Comment by SadBoyMaisAlegre** [comment] 2024-06-04 15:02
ok, Thanks for the update message, I'll test it

**Comment by SadBoyMaisAlegre** [comment] 2024-06-04 15:24
so I already tested, and still the same, load to 100% and then just close, both in offline and online mode

**Comment by SadBoyMaisAlegre** [comment] 2024-06-04 15:26
I normally downloaded the offline files, but it keeps closing by itself

**Comment by Admiral-Billy** [comment] 2024-06-04 22:13
I guess my hunch that the issue is ram-related might be true then, in which case there really isn't much else I can do about this :(

**Comment by SadBoyMaisAlegre** [comment] 2024-06-05 10:17
oh I see, most likely it should be the ram, so thx!

**Comment by Admiral-Billy** [comment] 2024-06-05 20:45
I'll close this one for now; sorry that it doesn't seem like there's a viable solution.

**Closed by Admiral-Billy** 2024-06-05 20:45 UTC
Labels: bug, question
