### ISSUE TITLE
Screen is whiter when press on start

### ISSUE THREAD

**Issue by maximehuran** [Admiral-Billy/Pokerogue-App#34] opened 2024-05-14 07:29 UTC
https://github.com/Admiral-Billy/Pokerogue-App/assets/11380627/a8656ebf-c906-4f01-9523-22cf7b7abc0c

When I launch the app from Ayn Odin 2, then I press the start button which opens the menu, the app is whiter.
It looks like a focus or something else is set and change the contrast of the image.

**Comment by Admiral-Billy** [comment] 2024-05-14 07:32
Oh I have no idea why it'd be doing that here, but whatever it's doing seems like it'd be an issue with PokeRogue itself rather than the app. If I actually had one of those I could try it myself, but alas.

**Comment by maximehuran** [comment] 2024-05-14 07:38
It could be an issue with PokeRogue itself, it also happened sometime on the web version in the browser (I saw it in Firefox but not Chrome)

**Comment by Admiral-Billy** [comment] 2024-05-18 11:00
For the time being I'll assume this is just a PokeRogue issue and close this here.

**Closed by Admiral-Billy** 2024-05-18 11:00 UTC
Labels: question

**Comment by sicarius273** [comment] 2024-06-13 02:44
I have this issue as well on my Retroid Pocket 4 Pro, and the issue is not present when using the web version of the app with Chrome. The issue goes away when the built in controller is disconnected at app boot, but returns when the controller is reconnected. I'm not a huge android guy, but it looks to me like the entire app is being 'highlighted' when the controller is plugged in, almost like the entire app window is a UI button if that makes sense.

**Comment by dickwhittington** [comment] 2024-10-28 04:37
I was able to resolve this on my retroid by disabling the "dark theme"
