### ISSUE TITLE
Missing Files freeze the game

### ISSUE THREAD

**Issue by Axelrasha** [Admiral-Billy/Pokerogue-App#12] opened 2024-05-08 16:18 UTC
Sorry, it's my first time submitting an issue, so I may be wrong on the analysis of the issue.

I was playing the offline mode, and my game suddently freezed. I checked in Devtools and find this error : 
![snowscape_not_found_err](https://github.com/Admiral-Billy/Pokerogue-App/assets/68515547/f24af362-73b5-4278-b64d-a647152e3db3)

And, it's true, the file is missing in local on my computer, so I checked in the code of pokerogue, the file is also missing.
I exported my data, and imported them on a local server I created following the instructions from : https://github.com/pagefaultgames/pokerogue to run locally

There I tried to reproduce the bug, but unfortunately, I didn't. It did work on my server (I have the file_not_found, but the game continue like nothing happened).
![snowscape_not_found_ok](https://github.com/Admiral-Billy/Pokerogue-App/assets/68515547/71a7d023-3509-4546-ad3c-0ed04bf68aae)

I don't know if you can do anything about this, since it seems that pokerogue-app, and my local server don't work the same.

But still, thank you for your work!

**Comment by GuiMouraIgnacio** [comment] 2024-05-08 21:54
I have the same issue, the workaround I found to continue my playtrough was to just duplicate a random battle-anim ("absorb.json" for example) and rename it to the one the game is trying to find

**Comment by Admiral-Billy** [comment] 2024-05-08 23:32
I'll have to look into this one more; it might just be a matter of adding some error handling.

**Comment by artman41** [comment] 2024-05-09 00:07
Similar issue, this one is for `battle-anims/zippy-zap.json`

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/5568965/384cf347-cd8d-4af9-be43-fb1ab3bdcf67)

**Comment by brskiiii** [comment] 2024-05-09 01:33
> Similar issue, this one is for `battle-anims/zippy-zap.json`
> 
> ![image](https://private-user-images.githubusercontent.com/5568965/329086001-384cf347-cd8d-4af9-be43-fb1ab3bdcf67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTg2NTEsIm5iZiI6MTcxNTIxODM1MSwicGF0aCI6Ii81NTY4OTY1LzMyOTA4NjAwMS0zODRjZjM0Ny1jZDhkLTRhZjktYmU0My1mYjFhYjNiZGNmNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDEzMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYwMGQyNWU3YTNiZGJjODM3MzM2Y2Y0NDZjODIwNjIyYmZkYTQ4NDk5YzE5MmI4YzBlMzNhYmY1NGQ5ZDQ5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._mprLfM7kVbrI3d8deYfY6yUEYA0LCAX3hAATR5umrI)

I had the same issue when my Eevee evolved to Espeon and it tried to learn Glitzy Glow.

**Comment by Admiral-Billy** [comment] 2024-05-09 07:15
I think I might've resolved this issue; try the latest version.

**Comment by MisterInSayne** [comment] 2024-05-09 10:31
Unfortunetly the problem persists. I have this same problem when Eevee evolves into Umbreon and tries to learn "Baddy bad" and when reaching encounter 90, where sadly I am now stuck.

**Comment by GuiMouraIgnacio** [comment] 2024-05-09 10:36
@MisterInSayne Please use the workaround I provided in the meantime, its super simple to setup. Then a quick game reload will work to continue your progress

**Comment by Admiral-Billy** [comment] 2024-05-09 11:25
> Unfortunetly the problem persists. I have this same problem when Eevee evolves into Umbreon and tries to learn "Baddy bad" and when reaching encounter 90, where sadly I am now stuck.

Just to clarify, you downloaded the new version of the app, not just the latest offline files, right? I posted a new app version with some fixes for stuff like that. Someone gave me a session save with zippy zap, and that one worked on the new version just fine. Of course, it could be some other issue, so I just want to make sure!

**Comment by EarthBet** [comment] 2024-05-09 12:31
This may be a separate issue, but my game is freezing as well. The first time was after I chose an item and it was supposed to switch to the next battle, the second time I was teaching my Bloodmoon Ursaluna a move and it froze on "And..."
I don't have the knowledge of HTML/json stuff needed to figure out if the cause is the same as it was for the others here or if it's a separate, related issue.

**Comment by GuiMouraIgnacio** [comment] 2024-05-09 12:38
@EarthBet the best way to check is to go to the top left menu when the game freezes, click on "toggle console", and send a printscreen of the console tab there, that should give all relevant information :)

**Comment by GuiMouraIgnacio** [comment] 2024-05-09 12:40
@Admiral-Billy thanks for the quick work. I am checking now if it solved it on my cases as well, will report here later Today

**Comment by Axelrasha** [comment] 2024-05-09 13:08
@Admiral-Billy I confirm, you have fixed my issue!
Thank you for your work!

**Comment by EarthBet** [comment] 2024-05-09 16:02
Froze again, this time I checked the console.

Failed to load resource: net::ERR_FILE_NOT_FOUND
images/battle_anims/PRAS-%20PsychicBG.png:1 

I tried to copy and paste and rename a different animation to be the missing one, but the file already existed. I thought maybe there wasn't a space between Psychic and BG like there were in other PRAS- Move BG.png files, so I tried renaming the copy to PRAS- PsychicBG.png instead, but it still froze.

**Comment by Axelrasha** [comment] 2024-05-09 16:12
Are you sure you have taken the new version with the fix? https://github.com/Admiral-Billy/Pokerogue-App/releases/tag/v2.0.1
Sorry to ask, but our issues look alike, and for me, the fix worked

**Comment by EarthBet** [comment] 2024-05-09 16:20
I assumed that downloading latest files for the game updated the game, but in retrospect I'm probably wrong. I'll try updating.

**Comment by EarthBet** [comment] 2024-05-09 16:29
Thank you, that fixed it

**Comment by Admiral-Billy** [comment] 2024-05-09 22:11
Alrighty, I'll close this for now since it *seems* like I stomped the issue. For any curious people, the online version gracefully handles missing animation files, but for some reason offline doesn't. I band-aid fixed this by just intercepting calls for missing files and returning an empty json file, but if there's a better fix out there let me know!

**Closed by Admiral-Billy** 2024-05-09 22:11 UTC

**Comment by artman41** [comment] 2024-05-10 22:09
@Admiral-Billy I saw your comment today so I did the `Download latest files for offline` then did a run but it looks like the bug is still a thing?

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/5568965/dc502d5f-d278-4d38-b2c0-c1f22687e690)

I reloaded in case the fix just wasn't being used and the 2nd time round I got a different error

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/5568965/2f266d3f-ba03-47f3-b1a5-79e4a0a69428)
